import { StyleSheet } from 'react-native';
import * as Color from './colors';

export default (Styles = StyleSheet.create({
  container: {
    flex: 1,
    marginLeft: 10,
    marginRight: 10,
    //backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  input: {
    width: 300,
    height: 44,
    padding: 8,
    borderWidth: 1,
    borderColor: '#757575',
    margin: 10,
  },
  btnGroup: {
    flex: 1,
    paddingBottom: 20,
    alignItems: 'center',
    justifyContent: 'flex-end',
    //alignSelf: 'flex-end',
  },
  btnPrimary: {
    backgroundColor: Color.primaryColor,
    borderColor: '#2e6da4',
    width: 150,
    margin: 5,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
  },
  btnSuccess: {
    backgroundColor: Color.successColor,
    borderColor: '#4cae4c',
    width: 150,
    margin: 5,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
  },
  btnInfo: {
    backgroundColor: Color.infoColor,
    borderColor: '#46b8da',
    width: 150,
    margin: 5,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
  },
  btnWarning: {
    backgroundColor: Color.warningColor,
    borderColor: '#eea236',
    width: 150,
    margin: 5,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
  },
  btnDanger: {
    backgroundColor: Color.dangerColor,
    borderColor: '#d43f3a',
    width: 150,
    margin: 5,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
  },
  btnText: {
    color: '#fff',
  },
  deckContainer: {
    flex: 5,
    marginLeft: 10,
    marginRight: 10,
    //backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  deckTitle: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  deckItem: {
    flex: 1,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 10,
    marginBottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deckLine: {
    marginTop: 5,
    marginBottom: 5,
    borderBottomWidth: 1,
    borderBottomColor: Color.orange,
    width: 350,
  },
}));
